#pragma once

// Minimal config for WASM build.
// Add more defines only if compilation complains.

#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MATH_H 1


// These are normally generated by the upstream CMake build.
#define CMAKE_INSTALL_PREFIX ""
#define CPACK_PACKAGE_VERSION_MAJOR 0
#define CPACK_PACKAGE_VERSION_MINOR 0
#define CPACK_PACKAGE_VERSION_PATCH 0